SELECTION_DICT = {
            "home runs": "homeRuns",
            "batting average": "battingAverage",
            "total bases": "totalBases",
            "assists": "assists",
            "shut outs": "shutouts",
            "sac bunts": "sacrificeBunts",
            "sac flies": "sacrificeFlies",
            "runs": "runs",
            "ground to fly ratio": "groundoutToFlyoutRatio",
            "stolen bases": "stolen:Bases",
            "ground outs": "groundOuts",
            "number of pitches": "numberOfPitches",
            "obp": "onBasePercentage",
            "caught stealing": "caughtStealing",
            "gidp": "groundIntoDoublePlays",
            "era":"earnedRunAverage",
            "fielding percentage" :"fieldingPercentage",
            "whip":"walksAndHitsPerInningPitched",
            "flyouts":"flyouts",
            "hbp":"hitByPitches",
            "games played":"gamesPlayed",
            "walks": "walks",
            "slugging": "sluggingPercentage",
            "ops": "onBasePlusSlugging",
            "rbis": "runsBattedIn",
            "triples": "triples",
            "xbh": "extraBaseHits",
            "hits": "hits",
            "ab": "atBats",
            "strike outs": "strikeouts",
            "doubles": "doubles",
            "total pa": "totalPlateAppearances",
            "intentional walks": "intentionalWalks",
            "wins": "wins",
            "losses": "losses",
            "saves": "saves",
            "wild pitches": "wildPitch",
            "air outs": "airOuts",
            "balks": "balk",
            "blown saves": "blownSaves",
            "catcher era": "catcherEarnedRunAverage",
            "catchers interferance": "catchersInterference",
            "chances": "chances",
            "complete games": "completeGames",
            "double plays": "doublePlays",
            "earned runs": "earnedRun",
            "errors": "errors",
            "games finishes": "gamesFinished",
            "games started": "gamesStarted",
            "hit batsman": "hitBatsman",
            "hits per nine": "hitsPer9Inn",
            "holds": "holds",
            "innings": "innings",
            "innings pitches": "inningsPitched",
            "outfield assists": "outfieldAssists",
            "passed balls": "passedBalls",
            "pickoffs": "pickoffs",
            "pitches per inning": "pitchesPerInning",
            "put outs":  "putOuts",
            "range factor per game": "rangeFactorPerGame",
            "range factor per nine": "rangeFactorPer9Inn",
            "save opportunities": "saveOpportunities",
            "stolen base percentage": "stolenBasePercentage",
            "strike outs per nine": "strikeoutsPer9Inn",
            "strike out to walk ratio": "strikeoutWalkRatio",
            "throwing errors": "throwingErrors",
            "total batters faced": "totalBattersFaced",
            "triple plays": "triplePlays",
            "walks per nine": "walksPer9Inn",
            "win percentage": "winPercentage",
                          }
FORMATTED_STATS = [
    'Home Runs',
    'Batting Average',
    'Total Bases',
    'Assists',
    'Shut Outs',
    'Sac Bunts',
    'Sac Flies',
    'Runs',
    'Ground To Fly Ratio',
    'Stolen Bases',
    'Ground Outs',
    'Number Of Pitches',
    'OBP',
    'Caught Stealing',
    'GIDP',
    'ERA',
    'Fielding Percentage',
    'WHIP',
    'Flyouts',
    'HBP',
    'Games Played',
    'Walks',
    'Slugging',
    'OPS',
    'RBIs',
    'Triples',
    'XBH',
    'Hits',
    'AB',
    'Strike Outs',
    'Doubles',
    'Total PA',
    'Intentional Walks',
    'Wins',
    'Losses',
    'Saves',
    'Wild Pitches',
    'Air Outs',
    'Balks',
    'Blown Saves',
    'Catcher Era',
    'Catchers Interferance',
    'Chances',
    'Complete Games',
    'Double Plays',
    'Earned Runs',
    'Errors',
    'Games Finishes',
    'Games Started',
    'Hit Batsman',
    'Hits Per Nine',
    'Holds',
    'Innings',
    'Innings Pitches',
    'Outfield Assists',
    'Passed Balls',
    'Pickoffs',
    'Pitches Per Inning',
    'Put Outs',
    'Range Factor Per Game',
    'Range Factor Per Nine',
    'Save Opportunities',
    'Stolen Base Percentage',
    'Strike Outs Per Nine',
    'Strike Out To Walk Ratio',
    'Throwing Errors',
    'Total Batters Faced',
    'Triple Plays',
    'Walks Per Nine',
    'Win Percentage'
          ]